apiVersion : apps/v1
kind: Deployment
metadata:
  name: "group4clust1-16e1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "group4clust1-16e1"
  template:
    metadata:
      labels:
        app: "group4clust1-16e1"
    spec:
      containers:
        - name: "group4clust1-16e1"
          image: "group4p2test.azurecr.io/group4clust1"
          ports:
          - containerPort: 80