apiVersion: v1
kind: Service
metadata:
    name: "group4clust1-16e1"
    labels:
        app: "group4clust1-16e1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "group4clust1-16e1"